### ISSUE TITLE
Any plan to add a file appender 

### ISSUE THREAD

**Issue by daveseco7** [catcher-in-the-try/objects-to-csv#1]
Hi,

With the current implementation, every time you write to the same file the previous file content will be overridden. Is there any plan to add a **file append**? I took a quick look at the code and I think `fs.appendFileSync()` would work as pretended, along with adding this as an optional argument.

Very handy dependency btw  
Cheers 😄

**Comment by catcher-in-the-try** [comment]
Thanks for the suggestion! This is now published on NPM as version `1.1.0`.

**Comment by catcher-in-the-try** [comment]
Sample:

```js
await new ObjectsToCsv(sampleData).toDisk('./test.csv', { append: true });
```

**Comment by daveseco7** [comment]
Thank you for the quick response and deliver! 🎉
