### ISSUE TITLE
Special characters are not supported

### ISSUE THREAD

**Issue by ngajhede** [catcher-in-the-try/objects-to-csv#2]
When I write a CSV file with characters liek the native danish Æ, Ø and Å its not encoded correctly. Is it possible that you can add an option to encode at UTF-8?

**Comment by catcher-in-the-try** [comment]
What you are seeing is actually a problem with Excel. If you open the same file in OpenOffice / LibreOffice, you will see that the file shows alright. 

Excel requires a "byte order mark" to be added at the beginning of CSV files to be able to show Unicode properly. 

So I've added a new option called `bom` which will add that BOM mark into the file:

```js
await csv.toDisk(testFilename, { bom: true });
```

Please get the latest version from NPM and you're set.

Thanks for the report!

**Comment by 10xchs** [comment]
This is not a fix. InDesign still can't show special characters.
